### ISSUE TITLE
Namespace 'QuickJSRaw' has no exported member 'QuickJSEmscriptenModule'

### ISSUE THREAD

**Issue by joshofreeness** [justjake/quickjs-emscripten#1]
Hi,

When trying to use the package in another typescript project, I get the error

```
/dist/quickjs.d.ts:3:68 - error TS2694: Namespace 'QuickJSRaw' has no exported member 'QuickJSEmscriptenModule'.

declare const QuickJSModule: import("./quickjs-emscripten-module").QuickJSEmscriptenModule;
```

I got the codebase building locally while trying to discover what the issue was, I noticed that the `quickjs-emscripten-module.d.ts` in the `ts` folder was different to the file that ended up in the `dist` folder after building.

Do you have any thoughts on this issue?

Thanks for your work on this project, very helpful 👍

**Comment by justjake** [comment]
I would expect that the Typescript compiler would copy the required declarations from the source .d.ts file into the emitted .d.ts file. Not sure if this issue comes from a bug in my understanding of Typescript or from a bug in the typescript.

**Comment by justjake** [comment]
This is fixed as of https://github.com/justjake/quickjs-emscripten/commit/f3ba10c72489351897a5df0870308e30c61e1944
Thanks for reporting!
