### ISSUE TITLE
Execute exported function?

### ISSUE THREAD

**Issue by FezVrasta** [justjake/quickjs-emscripten#107]
I'd like to make `evalCode` run a single user-provided function, exported as default by the user.

```js
export default function foo() { return 'bar'; }
```

I can't understand how to make it work, I tried this but I get a lifetime not alive error:

```js
const myVariable = vm.newNumber(2);
const result = vm.evalCode(userCode, 'eval.js', { type: 'module' });

if (result.error) {
  const error = result.error?.consume((error) => vm.dump(error));
  throw new Error(`Execution failed: ${error?.message ?? 'Unknown error'}`);
}

const configuration = result.value.consume((value) => {
  const result = vm.callFunction(value, vm.undefined, myVariable);
  myVariable.dispose();
  if (result.error) {
	const error = result.error?.consume((error) => vm.dump(error));
    throw new Error(`Execution failed: ${error?.message ?? 'Unknown error'}`);
  }
  return result.value.consume(value => vm.dump(value));
});

vm.dispose();
```

Could I get some help?

**Comment by real2two** [comment]
+1

**Comment by real2two** [comment]
One possible solution I found was doing `<QuickJSContext>.evalCode("yourFunction()")`.

**Comment by real2two** [comment]
No idea. I was trying to figure out a way too but gave up.

I haven't tested this code below that much yet, but I think you can do something like this to pass values safely.
```js
let value = 123;

if (typeof value === "function") {
    value = value.toString();
} else {
    value = JSON.stringify(value);
}

vm.evalCode(`globalThis.yourFunction(${value})`);
```

**Comment by justjake** [comment]
If your user has a module that export default a function, you can write your own module to get the handle to the user’s function, something like this:

```js
import userFn from “user”
globalThis.userFn = userFn
```

You’d need to do a single evalCode of your module, then you can get the handle via `const userFnHandle context.getProp(context.global, “userFn”)`. Finally to call the user’s function, `context.callFunction(userFnHandle, context.undefined, …)`

**Comment by justjake** [comment]
Module evaluation returns `undefined`

**Comment by FezVrasta** [comment]
Isn't that two evaluations? One for the user code and one for the import one?
