### ISSUE TITLE
Resolving a promise with an object creates undisposable references

### ISSUE THREAD

**Issue by joeltg** [justjake/quickjs-emscripten#118]
Hi! First of all, thanks so much for maintaining this library - such a cool and wacky piece of technology to be able to use!

As far as I can tell, resolving a `QuickJSDeferredPromise` with a heap-allocated value leaves a dangling reference somewhere that causes `vm.dispose()` to throw the dreaded `Assertion failed: list_empty(&rt->gc_obj_list)` error.

A simple reproduction is to take the [`newPromise` example from the readme](https://github.com/justjake/quickjs-emscripten#promises) and change it to return an object instead of a string literal

```ts
const content = fakeFileSystem.get(path)
// promise.resolve(vm.newString(content || ""))

const objectHandle = vm.newObject()
vm.newString(content || "").consume((contentHandle) =>
  vm.setProp(objectHandle, "content", contentHandle)
)

promise.resolve(objectHandle)
```

and try to call `vm.dispose()` at the end, I get

```
Result: { content: 'Example file content' }
Aborted(Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime)
/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/generated/emscripten-module.WASM_RELEASE_SYNC.js:75
            a.onAbort(b); b = "Aborted(" + b + ")"; D(b); H = !0; b = new WebAssembly.RuntimeError(b + ". Build with -sASSERTIONS for more info."); n(b); throw b; }
                                                                      ^

RuntimeError: Aborted(Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime). Build with -sASSERTIONS for more info.
    at F (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/generated/emscripten-module.WASM_RELEASE_SYNC.js:75:71)
    at a (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/generated/emscripten-module.WASM_RELEASE_SYNC.js:222:47)
    at wasm://wasm/001bd82a:wasm-function[607]:0x2cf8c
    at wasm://wasm/001bd82a:wasm-function[890]:0x48ef4
    at a._QTS_FreeRuntime [as QTS_FreeRuntime] (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/generated/emscripten-module.WASM_RELEASE_SYNC.js:306:82)
    at Lifetime.disposer (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/module.js:220:22)
    at Lifetime.dispose (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/lifetime.js:71:18)
    at Scope.dispose (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/lifetime.js:220:26)
    at QuickJSRuntime.dispose (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/runtime.js:124:27)
    at Scope.dispose (/Users/joel/Projects/canvas/node_modules/quickjs-emscripten/dist/lifetime.js:220:26)

Node.js v18.7.0
```

[Here's a gist with both complete examples](https://gist.github.com/joeltg/f0fcbf4a4be85893abb1a6741636f9da).

**Comment by joeltg** [comment]
Aha - after a little more investigation it turns I can use `deferred.settled.then` to immediately schedule disposing the value and it works:

```ts
promise.settled.then(() => objectHandle.dispose());
promise.resolve(objectHandle);
```

... but I feel like the runtime should be able to do this automatically, similar to return values of functions?

**Comment by justjake** [comment]
The reason I don’t do this automatically for DeferredPromise is that (IIRC) it’s used both for VM -> host promise and for host -> VM promise. So we shouldn’t assume a cleanup schedule for any promise we create. But as you call out about function calls, maybe we can assume that for host functions that return a promise to the VM, we can clean up automatically? But what if the VM hasn’t read the result before we clean up 🤔

**Comment by justjake** [comment]
When I try to reason about async lifetimes I get confused. I don’t want the library to dispose of borrowed values owned by a user’s code just because that value ended up in a promise.

**Comment by joeltg** [comment]
Oh wait - I can just `resultHandle.consume(promise.resolve)`, which is perfectly reasonable. I thought I had tried that right away at the start of this rabbit hole and it didn't work for some reason.

GitHub needs a 😵‍💫 react emoji.
