### ISSUE TITLE
`getQuickJS()` callback never resolves?

### ISSUE THREAD

**Issue by mitya33** [justjake/quickjs-emscripten#142]
Not sure what I'm doing wrong here. I'm trying to use this within a CloudFlare Worker. My code is taken from the demo:

```
import { getQuickJS, shouldInterruptAfterDeadline } from "quickjs-emscripten"
getQuickJS().then((QuickJS) => {
	console.log('start'); //<-- never happens
	const result = QuickJS.evalCode("1 + 1", {
		shouldInterrupt: shouldInterruptAfterDeadline(Date.now() + 1000),
		memoryLimitBytes: 1024 * 1024,
	})
	console.log(result)
})
```
It seems the callback is never entered. Any idea why that would be?

**Comment by justjake** [comment]
getQuickJS won’t work in Cloudflare due to their restrictions on WebAssembly compilation. To work in Cloudflare see this example: https://github.com/justjake/quickjs-emscripten/tree/main/examples/cloudflare-workers

**Comment by mitya33** [comment]
Ah OK, thanks for that. Would be great if you could flesh out the exact CF steps somewhat. I'm not sure, having read the link, what to do, but then my knowledge of WASM is low.

**Comment by justjake** [comment]
Start your cloudflare project by copying the example code in its entirety. I updated the README in the example to be more descriptive. Past that point I don't know what more I can say. The example code works, use it :)
