### ISSUE TITLE
[vite - MIME type Error]It's cannot work in vite

### ISSUE THREAD

**Issue by SuperLiii** [justjake/quickjs-emscripten#145]
i try to run the example `vite-vue` then i got some error in the browser (edge,chrome,firefox) 
I can't figure out where the problem is 

> - emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:87 
>  wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
>
> - emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:88 
>  falling back to ArrayBuffer instantiation
>
> - emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:80 
>failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
>
> - emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:50 
>  Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0)
A @ emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:50
>
> - emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:52 
> -Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -sASSERTIONS for more info.
>      at A (emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:52:11)
>      at emscripten-module.browser-N43QZIJR.js?v=e22dd2e0:81:9

even i try to using setting `vite.config.ts` like
```typescript
import { defineConfig } from 'vite';
export default defineConfig({
    server: {
        host: true
    },
    plugins: [
        {
            name: 'wasm',
            configureServer(server) {
                server.middlewares.use((req, res, next) => {
                    if (req.originalUrl.endsWith('.wasm')) {
                        res.setHeader('Content-Type', 'application/wasm')
                    }
                    next()
                })
            },
        },
    ],
})
```

by the way,i changed the package.json dependencies to ensure the smooth launch of the project
```json
{
  "name": "vite-vue",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@jitl/quickjs-ffi-types": "^0.26.0",
    "@jitl/quickjs-wasmfile-debug-asyncify": "^0.26.0",
    "@jitl/quickjs-wasmfile-debug-sync": "^0.26.0",
    "@jitl/quickjs-wasmfile-release-asyncify": "^0.26.0",
    "@jitl/quickjs-wasmfile-release-sync": "^0.26.0",
    "quickjs-emscripten": "^0.26.0",
    "quickjs-emscripten-core": "^0.26.0",
    "vue": "^3.3.11"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.5.2",
    "vite": "^5.0.8"
  }
}


```

**Comment by SuperLiii** [comment]
Okay, okay... think i found out how the problem occurred:

1. browser try to get file `emscripten-module.wasm` from `
http://localhost:5173/node_modules/.vite/deps/emscripten-module.wasm`
2. but the root `node_modules/.vite/deps/` dosen't have this
3. when i manually copied it over from package `quickjs-wasmfile-release-sync`, it's works!
4. that's why webpack can be run success,becase it's will be pack together

But I still don't know why the .wasm file wasn't automatically copied over.that's really strange.

**Comment by justjake** [comment]
Thanks for the issue report.

It's weird because `vite build` - which is what I was testing - seems to work fine with the default configuration, it's just the dev server that has this resolution issue. 

I updated the example in https://github.com/justjake/quickjs-emscripten/commit/e97f4ae13f490c9972eade70d964f67a3f85ef64 to use `newVariant` and a Vite URL import. This works with no vite.config.js change or manual copying, in both `vite` and `vite build`.

**Comment by sRect** [comment]
> Okay, okay... think i found out how the problem occurred:
> 
> 1. browser try to get file `emscripten-module.wasm` from ` http://localhost:5173/node_modules/.vite/deps/emscripten-module.wasm`
> 2. but the folder `node_modules/.vite/deps/` dosen't have this
> 3. when i manually copied it over from package `quickjs-wasmfile-release-sync`, it's works!
> 4. that's why webpack can be run success,becase it's will be pack together
> 
> But I still don't know why the .wasm file wasn't automatically copied over.that's really strange.

Now, But I got new Error:

```
QuickJSUnwrapError
    at M.unwrapResult (chunk-AM4WQSWV.js?v=cef4136d:563:57)
    at createRuntime (@sebastianwessel_quickjs.js?v=97444ee6:16905:23)
    at async run (App.tsx:83:26)
```

**Comment by justjake** [comment]
You should report the error to the wrapper library you are using, sebastianwessel_quickjs
