### ISSUE TITLE
How to access wasm module's Memory?

### ISSUE THREAD

**Issue by ppedziwiatr** [justjake/quickjs-emscripten#146]
Hey,

is it possible to access the wasm module's memory (i.e. the https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory) via the instance of the `QuickJS`, `runtime` or maybe `context`?

I would simply like to:
1. 'dump' and store the memory after evaluating the script
2. read the stored memory into the WASM module at the next evaluation

**Comment by justjake** [comment]
I looked into this a bit but didn't see a great way to do it in the Emscripten APIs. Access would be from the `QuickJSEmscriptenModule` class.

**Comment by justjake** [comment]
Actually, it seems possible.

**Comment by ppedziwiatr** [comment]
wow, that was _quick_ ;-) thank you!
