### ISSUE TITLE
TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by sradu** [justjake/quickjs-emscripten#151]
I'm trying to update to 0.27.0 and running into this error:

```
TypeError: Failed to construct 'URL': Invalid URL
    at emscripten-module.browser.mjs:11:445
```
<img width="473" alt="Screenshot 2024-02-07 at 4 17 12 PM" src="https://github.com/justjake/quickjs-emscripten/assets/82214/255bd11d-bc32-4671-b24a-79d8ff6a1c67">

with the code:

```
import { getQuickJS } from 'quickjs-emscripten'

export class UIVM  {
  async setupVM () {
    const QuickJS = await getQuickJS()
    console.log('never get here')
    const runtime = QuickJS.newRuntime()

    this.vm = runtime.newContext()
  }
}
```
My environment is Rails + esbuild + yarn. I'm unsure where to start debugging this, the integration is just yarn add and this code above.

**Comment by exoego** [comment]
I encountered this.
It looks like an issue in ESBuild. It does not work with `new URL(..., import.meta.url)` 
 as of today?
https://github.com/evanw/esbuild/issues/795

**Comment by sradu** [comment]
Since that ticket is from 2021 it's likely they won't provide a fix. Have you found a workaround?

**Comment by justjake** [comment]
@sradu you can switch to a “singlefile” variant for your release build. See the instructions here: https://github.com/justjake/quickjs-emscripten/blob/main/doc/quickjs-emscripten-core/README.md

**Comment by sradu** [comment]
Thanks for the quick reply @justjake.

If I want to use two engines, one async, and one regular, and consequently include those 2 out of 4 engines in the payload, is that possible?

In one place I'm using `getQuickJS` and in another `newQuickJSAsyncWASMModule`.

**Comment by sradu** [comment]
I have this now:

```
import { newQuickJSWASMModuleFromVariant } from 'quickjs-emscripten-core'
import releaseVariant from '@jitl/quickjs-singlefile-cjs-release-asyncify'

async setupVM () {
    console.log('xx', releaseVariant)
    const module = await newQuickJSWASMModuleFromVariant(releaseVariant)
    const runtime = module.newRuntime()
    this.vm = runtime.newContext()

    console.log('here', this.vm.evalCodeAsync)
}
```

`this.vm.evalCodeAsync` is null.
<img width="477" alt="Screenshot 2024-02-07 at 9 06 11 PM" src="https://github.com/justjake/quickjs-emscripten/assets/82214/54cd9cd8-6480-435f-9d5d-a18306e7f84d">

Also, the main docs say
```
import { newQuickJSWASMModuleFromVariant } from "quickjs-emscripten-core"
import DEBUG_SYNC from "@jitl/quickjs-wasmfile-debug-sync"

const QuickJS = await newQuickJSWASMModuleFromVariant(DEBUG_SYNC)
```
whereas the other page says:
```
import releaseVariant from "@jitl/quickjs-singlefile-cjs-release-sync"

// 3. Create the "QuickJS" module that presents the quickjs-emscripten API.
//    Export and use in other files, or consume directly.
const QuickJS = await newQuickJSWASMModuleFromVariant(releaseVariant)
```

**Comment by sradu** [comment]
OK figured it out, had to read the docs carefully:

for async
```
import { newQuickJSAsyncWASMModuleFromVariant } from 'quickjs-emscripten-core'
import releaseVariant from '@jitl/quickjs-singlefile-cjs-release-asyncify'

async setupVM () {
   const module = await newQuickJSAsyncWASMModuleFromVariant(releaseVariant)
    const runtime = module.newRuntime()
    this.vm = runtime.newContext()
}
```

for sync
```
import { newQuickJSWASMModuleFromVariant } from 'quickjs-emscripten-core'
import releaseVariant from '@jitl/quickjs-singlefile-cjs-release-sync'


  async setupVM () {
    const module = await newQuickJSWASMModuleFromVariant(releaseVariant)
    const runtime = module.newRuntime()

    this.vm = runtime.newContext()
  }
```

Thank you @justjake. Apologies for the message spam.

The main docs *could* be a bit less confusing, but what you're doing is amazing and we should pay more attention.

**Comment by justjake** [comment]
Do you have any suggestions on how to improve the docs? I end up pretty blind to the issues because I’m too deep  😅
