### ISSUE TITLE
Distributed packages have no license

### ISSUE THREAD

**Issue by peterwoodworth** [justjake/quickjs-emscripten#157]
Hello QuickJS team, 

Some of your distributed packages from this repository contain no licensing information. I assume everything in this repository is licensed under MIT, but when installing some packages like `@jitl/quickjs-ffi-types`, I can see they don't contain any information regarding their licensing, which can make it difficult to discern what rights we have and also create attribution documents.

Would be helpful if the LICENSE file could be added to your distributed packages, thank you!

**Comment by justjake** [comment]
What are you looking for specifically? A field in package.json? A file?

**Comment by justjake** [comment]
Published with v0.29.0
