### ISSUE TITLE
Codesandbox.io doesn't respect package.json import conditions

### ISSUE THREAD

**Issue by mehmetron** [justjake/quickjs-emscripten#183]
First off, thanks for making this library publicly available! It's awesome!

The full error is:

> Uncaught SyntaxError: Cannot use 'import.meta' outside a module
>     at eval (<anonymous>)
>     at z (sandbox.275a9407e.js:1:94080)
>     at K.evaluate (sandbox.275a9407e.js:1:106841)
>     at ve.<anonymous> (sandbox.275a9407e.js:1:115700)
>     at Generator.next (<anonymous>)
>     at i (sandbox.275a9407e.js:1:112149)

Sandbox where error takes place: https://codesandbox.io/p/sandbox/quickjs-emscription-forked-z48jf6

Sandbox with old version that works: https://codesandbox.io/p/sandbox/quickjs-emscription-pgf0f

Are you guys also getting this error? Didn't seem like it was related to my main javascript code but, instead, related to the wasm runtime

**Comment by mehmetron** [comment]
Version 0.24.0 seems to be the last version before things start breaking in this sandbox:

https://codesandbox.io/p/sandbox/quickjs-emscription-forked-94k495

**Comment by sradu** [comment]
@mehmetron is this other issue helpful https://github.com/justjake/quickjs-emscripten/issues/151? I believe I ran into that too.

**Comment by justjake** [comment]
Yeah, I recommend the single file builds if the multifile ones don’t work well for you. Since this is a continued issue, I may reverse the defaults back to “singlefile”. The split build does have better instantiation performance since it can be cached by the browser but it requires a very “modern” JavaScript built pipelin
