### ISSUE TITLE
How to handle Buffer

### ISSUE THREAD

**Issue by sebastianwessel** [justjake/quickjs-emscripten#189]
Hey,

I'm currently working on my own small [QuickJS lib](https://github.com/sebastianwessel/quickjs), based on quickjs-emscripten and I try to add support for `Buffer`. 
Generally, I have a polyfill for `Buffer`, which can be used as import (`import {Buffer} from 'node:buffer'`).

But I'm really struggling on exchanging Buffer from host to QuickJS and from QuickJs to host.

**Comment by justjake** [comment]
Someone contributed newArrayBuffer / getArrayBuffer although there’s been some bug reports that they aren’t working. Try it out: https://github.com/justjake/quickjs-emscripten/blob/main/doc/quickjs-emscripten-core/classes/QuickJSContext.md#getarraybuffer
