### ISSUE TITLE
Increase the lifetime of function arguments (clone handles?)

### ISSUE THREAD

**Issue by arcanis** [justjake/quickjs-emscripten#19]
What's the best way to store an handle into a storage for later use? Since arguments are currently automatically cleaned after the function returns, it seems any attempt to do so will result in "Lifetime not alive" exceptions.

**Comment by justjake** [comment]
Memory management / lifetime management is the most troublesome aspect of this library. I've pondered a "pool" or "arena" abstraction in native javascript land, but didn't find a design with satisfying ergonomics.

For now, you might try storing your borrowed QuickJS handles on an object you own inside the the QuickJS runtime. Like so:

```typescript
const box = vm.createObject()
const fnHandle = vm.createFunction('onComplete', (_this, errorHandle, resultHandle) => {
  if (vm.typeof(errorHandle) === 'undefined') {
    vm.setProp(box, 'value', resultHandle)
  }
})
vm.setProp(vm.global, 'onComplete', fnHandle)
fnHandle.dispose()
```

If you're interested in implementing something like `functionArgumentHandle.toOwned()`,  I believe it would be possible without writing any C code, as we already have *two* FFI-exposed functions (oops 🤦) that do so, here is the one I'd prefer to use:

https://github.com/justjake/quickjs-emscripten/blob/1329af50d939a4d758122b22533107456fa0a30a/ts/ffi.ts#L172-L173
