### ISSUE TITLE
Register multiple separate interrupt handlers

### ISSUE THREAD

**Issue by endercrest** [justjake/quickjs-emscripten#191]
Hey! Got a use case where it would be valuable to be able to register multiple separate interrupt handlers to the same runtime without overriding the already registered handler.

I am currently writing an abstraction that makes it so you can provide multiple middlewares that modify / alter the runtime. Currently, I have to pass some information around externally in order for these middlewares to be aware that there may already be an interrupt handler registered. It would be nice if this was just supported already by the runtime.

I am happy to take a stab at implementing this if there isn't any concern / reason not to do this.

**Comment by justjake** [comment]
Is there any reason you can't multiplex the handlers in userspace, like this?

```typescript
class InterruptHandlerRegistry {
  private handlers = new Set<InterruptHandler>()

  add(handler: InterruptHandler) { this.handlers.add(handler) }
  remove(handler: InterruptHandler) { this.handlers.remove(handler) }

  interruptHandler: InterruptHandler = (runtime) => {
    for (const handler of this.handlers) {
      if (handler(runtime)) return true
    }
    return false
  }
}

const interruptHandlerRegistry = new InterruptHandlerRegistry()
const runtime = QuickJS.newRuntime()
runtime.setInterruptHandler(registry.interruptHandler)

someMiddlewareThingy({ runtime, interruptHandlerRegistry })
```

**Comment by justjake** [comment]
Going to close as I think it’s totally fine to handle this in user space.
