### ISSUE TITLE
Ability to clone context

### ISSUE THREAD

**Issue by tim-field** [justjake/quickjs-emscripten#192]
My use case here applying polyfills to a context ( which can be slow ).  Then cloning this context as required to avoid the polyfill initiation time. 

A possible approach is discussed here https://github.com/justjake/quickjs-emscripten/issues/152

I'm wondering if this approach would make sense in a context.clone() method ?

**Comment by justjake** [comment]
What would the context.clone() method do?

**Comment by tim-field** [comment]
I was thinking give me an instance of context at a given point(er) ( ie post polyfil )

**Comment by justjake** [comment]
You can already pass a `contextPointer` as part of the `module.createContext(options)` or `runtime.createContext(options)` methods. These options are public as far as Typesript is concerned, but may not be documented. If you need a change to related APIs, h passing arbitrary runtime pointers to `module.createRuntime`, I'd be happy to accept such a PR
