### ISSUE TITLE
How to de-duplicate calls to an async host function?

### ISSUE THREAD

**Issue by damiencourouble** [justjake/quickjs-emscripten#198]
Hello there,

I'm using asyncify and I'm defining a few asynchronous functions to the context using `context.newAsyncifiedFunction(`
I use `context.evalCodeAsync(mycontent);` to evaluate the result of `mycontent`
Everything works great but I just noticed that if I have a content such as 
`asyncFuncA() + asyncFuncA() + 10 + whatever +  asyncFuncA() `

Three differents asynchronous calls are made, In my case since asyncFuncA triggers an ajax call I'd love to understand how I can only limit evalCodeAsync to produce only one trigger of the handle of asyncFuncA and return the result to each calls.

Thanks :)

**Comment by justjake** [comment]
Do whatever you'd normally do to de-duplicate calls to a function. There's nothing special about this async function being called from quickjs-emscripten client code when it comes to implementing this functionality. I would suggest structuring the code to separate the backend behavior implemented in the host, here represented by `interface AsyncService`, with the code that exposes the `AsyncService` to the VM. I would suggest three layers:
- The service implementation, which is concerned only with correct call semantics and result parsing/handling.
- A layer that handles de-duplication, rate limiting, abuse prevention, etc. You can think of this layer as middleware that takes an `AsyncService` and returns a new `AsyncService` that is safe for untrusted code to call.
- A layer than handles binding an `AsyncService` instance into a QuickJSContext. This layer handles converting to/from QuickJSHandle, etc.

```typescript
// Common interface that all layers implement
interface AsyncService {
  asyncFuncA(args: AArgs): Promise<AResult>
}

// Backend
class AsyncServiceBackend implements AsyncService {
  async asyncFuncA(args: AArgs): Promise<AResult> {
    // pure io: just do asyncFuncA things
    return (await fetch(...)).json()
  }
}

// Safety middleware
function deDuplicateCalls<Args extends unknown[], Result>(fn: (...args: Args) => Promise<Result>): (...args: Args) => Promise<Result> {
  // return a function that de-duplicates its calls
  const currentCalls = ...
  return (...args: Args) => {
    const currentCall = currentCalls.getPendingCall(args)
    if (currentCall) { return currentCall }
    const result = fn(...args)
    currentCalls.setPendingCall(args, result)
    return result
  }
}

class SafeAsyncApi implements AsyncService {
  constructor(private backend: AsyncService) {
    this.asyncFuncA = deDuplicateCalls(async (args: AArgs): Promise<AResult> {
      this.rateLimit('asyncFuncA')
      return this.backend.asyncFuncA(args)
    })
  }

  private rateLimit(name: string) { ... }
}

// Binding layer
function createGuestService(service: AsyncService, context: QuickJSContext): QuickJSHandle {
  const resultHandle = context.newObject()
  using funcHandle = context.newAsyncifiedFunction((thisHandle, argsHandle) => {
    const args = ...
    const result = service.asyncFuncA(args)
    const resultHandle = ...
    return resultHandle
  })
  context.setProp(resultHandle, 'asyncFuncA', funcHandle)
  return resultHandle
}
```

By separating concerns this way:
- Your backend code remains very simple and easy to modify as the backend changes
- You can unit test your safety/de-dupe behavior without making any calls to your backend
- You can unit test the binding behavior without getting confused by de-duped or rate-limited calls
