### ISSUE TITLE
How do I call the methods of a class instance?

### ISSUE THREAD

**Issue by ashamsutdinov-Deltek** [justjake/quickjs-emscripten#199]
Hello,

I'm trying to figure out how I can pre-compile a class (really a module with classes) and call it's methods subsequently.

Something like:

const classHandle = vm.newClass('
class A {
   myMethod(b) {
     return "Hello" + b + "!";
   }
}
');
classHandle.callMethod("myMethod", "World");

How can this be done?

:)

**Comment by ashamsutdinov-Deltek** [comment]
Found:

https://github.com/justjake/quickjs-emscripten/blob/main/doc/quickjs-emscripten/interfaces/ContextEvalOptions.md

compile but do not run. The result is an object with a JS_TAG_FUNCTION_BYTECODE or JS_TAG_MODULE tag. It can be executed with JS_EvalFunction().

But I can't find any documentation on how to access JS_EvanFunction

**Comment by justjake** [comment]
I’m not sure what the difference between your hypothetical `context.newClass` method and what the existing `evalCode` method does. If you want a handle to an instance of a class, you can return that from your eval, or export the class or an instance of the class if you eval as module.

**Comment by ashamsutdinov-Deltek** [comment]
> I’m not sure what the difference between your hypothetical `context.newClass` method and what the existing `evalCode` method does. If you want a handle to an instance of a class, you can return that from your eval, or export the class or an instance of the class if you eval as module.

That's what I'm a struggling with - looking at the examples in the documentation I get the impression that what's returned is a static value, something compiled that executes.  I don't get how I'll execute methods on the returned objects (the API to do so) - will try ...

**Comment by ashamsutdinov-Deltek** [comment]
Tried this, callFunction returned an error object, not sure what I'm doing wrong:
`
<!doctype html>

<script type="module">
  import { getQuickJS } from "https://esm.sh/quickjs-emscripten@0.25.0"
  const QuickJS = await getQuickJS()
  // QuickJS.setModuleLoader(dontKnowWhereToGetItOrIfItsNeeded)
  const vm = QuickJS.newContext()
  const greeter = vm.evalCode(`
  export class A {
    hello(who) {
      return 'Hello ' + who + '!';
    }
  }
  var greeter = new A()
  export default greeter
`)
  const hello = vm.getProp(greeter, 'hello')
  const wrappedResult = vm.callFunction(hello, greeter, vm.newString("World"))
  console.log(vm.unwrapResult(wrappedResult));
</script>
`

**Comment by ashamsutdinov-Deltek** [comment]
This doesn't work either:
```
<script type="module">
  import { getQuickJS } from 'https://esm.sh/quickjs-emscripten@0.29.2'
  const QuickJS = await getQuickJS()
  // QuickJS.setModuleLoader(dontKnowWhereToGetItOrIfItsNeeded)
  const vm = QuickJS.newContext()
  const module = vm.evalCode(`
  export class A {
    hello(who) {
      return 'Hello ' + who + '!';
    }
  }
  export var greeter = new A()
`)
  const greeter = vm.getProp(module, 'greeter')
  const hello = vm.getProp(greeter, 'hello')
  const wrappedResult = vm.callFunction(hello, greeter, vm.newString("World"))
  console.log(vm.unwrapResult(wrappedResult))
</script>
```

**Comment by ashamsutdinov-Deltek** [comment]
was dumping the error value incorrectly:

console.log(vm.dump(wrappedResult.value))

got:

runtime.ts:327 Uncaught TypeError: Cannot read properties of undefined (reading 'owner')
    at ie.assertOwned (runtime.ts:327:16)
    at re.dump (context.ts:973:18)
    at quickJsTest.html:20:18

**Comment by justjake** [comment]
That error is because `wrappedResult.value` is undefined, eg wrappedResult is an error

**Comment by justjake** [comment]
Use this pattern: `vm.dump(vm.unwrapResult(result))` 
it will throw result.error if result is an error

**Comment by justjake** [comment]
Working with modules is a bit confusing, sometimes they return a Promise<Module>. Try instead setting your thing on globalThis, then it's easy to access:
```typescript
class A {
  something() { return 'something' }
  else() { return this.something() + ' else' }
}
globalThis.A = A
globalThis.a = new A
```

See this example: https://github.com/justjake/quickjs-emscripten?tab=readme-ov-file#interfacing-with-the-interpreter

**Comment by ashamsutdinov-Deltek** [comment]
Still not getting the idea.  Tried to apply the example and unwrapped everything (which just results in pointers to objects, I guess).  Still not working. :(

```
import { getQuickJS } from 'https://esm.sh/quickjs-emscripten@0.29.2'
  const QuickJS = await getQuickJS()
  // QuickJS.setModuleLoader(dontKnowWhereToGetItOrIfItsNeeded)
  const vm = QuickJS.newContext()
  console.log(vm.dump(vm.evalCode(`"Hello World!"`).value))
  // const greeter = vm.evalCode(`
  const module = vm.evalCode(`
  export class A {
    hello(who) {
      return 'Hello ' + who + '!';
    }
  }
  globalThis.greeter = new A()
`)
  const unwrappedModule = vm.unwrapResult(module)
  console.log(vm.dump(unwrappedModule))
  const greeter = vm.unwrapResult(vm.getProp(unwrappedModule, 'greeter'))
  const hello = vm.unwrapResult(vm.getProp(greeter, 'hello'))
  const wrappedResult = vm.callFunction(hello, greeter, vm.newString("World"))
  console.log(vm.dump(vm.unwrapResult(wrappedResult)))
```

**Comment by justjake** [comment]
globalThis approach:

```javascript
import { getQuickJS } from "https://esm.sh/quickjs-emscripten@0.29.2"
const QuickJS = await getQuickJS()
const context = QuickJS.newContext()
const r1 = context.unwrapResult(
  context.evalCode(`
    globalThis.Greeter = class Greeter {
      getGreeting() { return "hello" }
      greet(name) { return this.getGreeting() + " " + name }
    }
    globalThis.greeter = new Greeter
  `),
)
const greeter = context.getProp(context.global, "greeter")
const greet = context.getProp(greeter, "greet")
const name = context.newString("Jesse")
const r2 = context.unwrapResult(context.callFunction(greet, greeter, name))
console.log(context.dump(r2)) // "hello Jesse"
```

module approach:

```javascript
import { getQuickJS } from "https://esm.sh/quickjs-emscripten@0.29.2"
const QuickJS = await getQuickJS()
const context = QuickJS.newContext()
const moduleExports = context.unwrapResult(
  context.evalCode(`
    export class Greeter {
      getGreeting() { return "hello" }
      greet(name) { return this.getGreeting() + " " + name }
    }
    export const greeter = new Greeter
  `),
)
const greeter = context.getProp(moduleExports, "greeter")
const greet = context.getProp(greeter, "greet")
const name = context.newString("Jesse")
const r2 = context.unwrapResult(context.callFunction(greet, greeter, name))
console.log(context.dump(r2)) // "hello Jesse"
```

**Comment by ashamsutdinov-Deltek** [comment]
Thank you much!  Module is the one I'm after - works perfectly.  :)
