### ISSUE TITLE
Is there a way to get the metadata (memory, heap consumption, elapsed time, etc.) after running `evalCode`

### ISSUE THREAD

**Issue by huypham50** [justjake/quickjs-emscripten#204]
Sorry if I miss this in the docs -- great library!

**Comment by justjake** [comment]
Elapsed time you can track yourself in user-space or with runtime.setInterruptHandler. For memory usage, see [runtime.computeMemoryUsage](https://github.com/justjake/quickjs-emscripten/blob/main/doc/quickjs-emscripten-core/classes/QuickJSRuntime.md#computememoryusage) (or .dumpMemoryUsage for human-readable output)

```typescript
console.log(context.runtime.dumpMemoryUsage())
const usageInfoObject = context.runtime.computeMemoryUsage().consume(context.dump)
```
