### ISSUE TITLE
Memory handling

### ISSUE THREAD

**Issue by keverw** [justjake/quickjs-emscripten#24]
https://bellard.org/quickjs/quickjs.html#Memory-handling

It looks like quickJS can let memory limits, that would be useful if you wanted to let users upload their own functions but limit the amount of allowed memory. Being able to get the current memory usage, such as profiling too. I see there is a way to dump memory usage in QuickJS. If so, then someone could use that and the termination hooks to write their own logic to enforce memory usage.

Also be useful if the Execution timeout and interrupts timeouts was there. Could see this maybe being useful for things you might use V8 Isolates for, but not sure if this would be lighter weight on the memory side.

Very interesting project though, could see this being useful on both the server side and client side too. Say if you were making a virtual world or a game engine, could let people run sandbox limited server scripts or even local scripts on the client side.

**Comment by justjake** [comment]
Exposing the memory limit and stack size limit APIS is a good idea.

We already expose the interrupt handler api: https://github.com/justjake/quickjs-emscripten/blob/master/doc/classes/quickjsvm.md#setshouldinterrupthandler

**Comment by keverw** [comment]
Yeah, was digging in the docs and seen setShouldInterruptHandler on the API level. I got the v8 isolates working but it seemed a base empty script used about 500KB, and if you wanted to run 100s or even thousands, that'd add up quick. So was hoping maybe this project would have lower memory but haven't been able to tell yet. Not sure if it'd be possible to measure total script runtime too, then my own logic could check it and enforce limits or provide it for debugging.

I want to play with this some more, hoping could get async stuff working too seems possible but need to play with it. So say a script got an event, could async call a inside function that's outside the vm to say write to the database for example and either resolve/reject it back to their own logic.

**Comment by keverw** [comment]
Thanks for getting that added 👍 
I'm guessing my idea to monitor CPU usage probably isn't possible? I'm guessing QuickJS would have to have that in it first if so? Was thinking it'd be cool to get script runtime/cpu usage type of thing.

**Comment by keverw** [comment]
Neat :) Seen you pushed to NPM! I updated and ran the test code. Very nice, a lot less overhead. Really wish there was a way to handle CPU time/limiting but I guess that'd have to be done either via QuickJS itself or maybe some other thing using the WASM thing, so I guess that'd be out of scope. I plan to rate limit API calls from the VM to the script but one of my worries is some script could take up a lot of CPU and crash other things. So unsure on that issue.

Looks like some other projects did a thing called metering with WASM. Looks like there's a lib called wasmer that is working on that but seen a bug report relating to that... I'd guess you'd have to instantiate a separate copy of the WASM for something like that to work though...

I know another idea is to just limit total time a script could run, but my idea is to just let them run until the next reboot and be ready if keeping small. So not sure how to approach this risk, be cool if there was an API to get CPU usage type info sorta like Windows Task Manage or Mac's Activity Monitor...  but very impressed so far! With the other engine an empty script was almost half a meg and this gets down to around 30KB! Then even opens up the possibility of sandboxed local scripts too since some other game engines allow stuff to run either server side or local. So very impressed so far, exciting to follow this tech.

**Comment by justjake** [comment]
I think the shouldInterruptHandler can implement the budgeting you describe. The interrupt handler is invoked regularly every 1000 instructions or so, so you can implement a time-based or instruction count based budgeting for each vm.

**Comment by keverw** [comment]
Neat. I'll have to dig into this more. Still got other things to get done but scripting was one thing that been worrying me. Very cool exciting stuff though! I guess only very recently possible too.
