### ISSUE TITLE
How to register an async callback and return with Promises

### ISSUE THREAD

**Issue by neeboo** [justjake/quickjs-emscripten#28]
Still dont know how to make an async function by now.

**Comment by justjake** [comment]
Hi @neeboo - can you show an example? Or otherwise provide more information?

* Do you want to perform a function call from QuickJS to the host that returns a Promise to QuickJS?

* Do you want to perform a function call from the host to code inside QuickJSVm that returns a Promise to the host?

It may help to think about making a callback-based API first, that you wrap in Promises instead of a “promise-native” style.

**Comment by justjake** [comment]
The Promise constructor is available via the VM’s `vm.global`

**Comment by neeboo** [comment]
> Hi @neeboo - can you show an example? Or otherwise provide more information?
> 
> * Do you want to perform a function call from QuickJS to the host that returns a Promise to QuickJS?
> * Do you want to perform a function call from the host to code inside QuickJSVm that returns a Promise to the host?
> 
> It may help to think about making a callback-based API first, that you wrap in Promises instead of a “promise-native” style.

1. Suppose that we have global object in the host:
  ```javascript
  global = {
        ...
  }
 ```
  now, we can register an function using C or VM's `vm.newFunction`, and attach it to `global.testObj`.

  question is, how do we create an async function using `vm.newFunction`? it seems that it is sync-style.

  I hope I can make a callback function which can be created by vm methods or C methods.

  which suppose to be:
  ```javacript```
  // vm side
  const async_handle= vm.newAsyncFunction('testAsync', async (...args)=>{

     const result= await someOtherPromiseFunc(args); // do something with args, may be we call async network execution, like `fetch`? or do some expensive execution?
    return result; // return Promise value to vm->host
  })

  ...

  vm.defineProp(..., async_handle,...); // attach to global or it's prop 

  ```
 and to the host side
   
 ```javascript

  global.testAsync(1).then(val=>...) // call async callback and returned by Promise
```

**Comment by justjake** [comment]
@neeboo quickjs.h does not expose a C API for creating a Promise. Instead I think it's fine to write some glue code like this. Note that I haven't tested this at all, and I'm omitting memory management (disposing of handles, etc) for the sake of writing in a github comment.

```typescript
function newDeferredHandle(vm) {
  const deferred = vm.evalCode(`
  const result = {};
  result.promise = new Promise((resolve, reject) => {
    result.resolve = resolve
    result.reject = reject
  });
  result;
 `)
  // should always succeed
  return vm.unwrap(deferred)
}

// create async function that wraps host `fetch`
const async_handle = vm.newFunction('fetch', (urlHandle) => {
  const url = vm.dump(urlHandle)
  const deferredHandle = newDeferredHandle(vm)
  const nativeFetchPromise = fetch(url)
  nativeFetchPromise.then(response => response.text()).then(text => {
    vm.callFunction(vm.getProp(deferredHandle, 'resolve'), vm.newString(text))
  }).catch(error => {
    vm.callFunction(vm.getProp(deferredHandle, 'reject'), vm.newString(error.message))
  })
  return vm.getProp(deferredHandle, 'promise')
})

// expose to VM 
vm.setProp(vm.global, 'fetch', async_handle)
```

The shared parts (creating the deferred, wrapping a native promise) could be extracted to `vm.newAsyncFunction`.

**Comment by neeboo** [comment]
@justjake Thanks for replying, it definitely worth a try.

**Comment by justjake** [comment]
Actually, there is a public C api to create a Promise/deferred which should be faster than using evalCode. It must have been added in a more recent QuickJS release. I’ll put together a wrapper.

**Comment by justjake** [comment]
@neeboo PR with `vm.newPromise()` api and some documentation: https://github.com/justjake/quickjs-emscripten/pull/29

**Comment by neeboo** [comment]
> @neeboo PR with `vm.newPromise()` api and some documentation: #29

Thanks, I'll test and give you some feedback here. And i'll try to port them to dart version.
