### ISSUE TITLE
Checking if a function with a given name exists?

### ISSUE THREAD

**Issue by mvanga** [justjake/quickjs-emscripten#38]
Hey,

First, thanks for the great project! I've been toying around with quickjs-emscripted in the browser but am running into a minor issue. I'm trying to call a function inside a VM, but only if the user has defined it. The following currently works as expected:

```js
vm.evalCode('function hello() { return 42; }');
const handle = vm.getProp(vm.global, 'hello');
let result = vm.callFunction(handle, vm.undefined);
if (result.error) {
  console.log('calling function failed')
} else {
  console.log('success', vm.getNumber(result.value));
}
```

If the user hasn't defined the particular function being called, I can handle it in the error case. However, I'm wondering if there's a more elegant way to do this without having to handle the error. Would it be possible to hack up a `checkFunctionHandle()` function?

Thanks again!

**Comment by justjake** [comment]
You can use [`vm.typeof(handle)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof), which returns a string describing the type of the handle.
If the function wasn't defined, `vm.typeof` will return `undefined` here. If it's a function, it will return `function`.

Example:

```typescript
vm.evalCode('function hello() { return 42; }');
const maybeFnHandle = vm.getProp(vm.global, 'hello');
if (vm.typeof(maybeFnHandle) === 'function') {
  vm.callFunction(handle, vm.undefined);
}
```
