### ISSUE TITLE
Illegal invocation error with quickjs-emecripten-sync

### ISSUE THREAD

**Issue by emilmuller** [justjake/quickjs-emscripten#41]
Hi

I'm trying something very naughty:

`arena.expose({ mydiv: document.createElement("div") });`

and then

`console.log(arena.evalCode('() => mydiv.tagName')());`

but am left with this:

```
quickjs.js:651 Uncaught (in promise) TypeError: Illegal invocation
    at QuickJSVm.unwrapResult (quickjs.js:651)
    at eval (quickjs-emscripten-sync.modern.js:18)
    at h (quickjs-emscripten-sync.modern.js:18)
    at eval (quickjs-emscripten-sync.modern.js:18)
    at eval (app.tsx:55)
```

I guess I'm violating some rule that maybe is documented somewhere? :)

P.S. Awesome work!

**Comment by justjake** [comment]
Perhaps your question pertains to quickjs-emscripten-sync, the library that appears higher in your stack trace and that implements the function you are calling.

**Comment by emilmuller** [comment]
Oh right! Sorry. I see there's a lot I haven't read regarding marshaling. Sorry for the inconvenience. I'll close this for now
