### ISSUE TITLE
Having troubles setting a getter onto an object def

### ISSUE THREAD

**Issue by ScriptedAlchemy** [justjake/quickjs-emscripten#47]
Hey! 

Im trying to create a global object that uses descriptors like get and set, however im not able to get past this error

![image](https://user-images.githubusercontent.com/25274700/143506756-93bfb6ae-9365-4e0a-9a3b-517fe925a9e5.png)

As soon as i comment out the `get` it runs with no errors. 

However i also see that even when it throws an error, i am still calling the get() method before the application crashed. 

I tried taking the source from one of your tests & still no dice

```  
vm.defineProp(vm.global, 'Name', {
    enumerable: true,
    configurable: true,
    get: () => vm.newString('World'),
  })
  ```

**Comment by justjake** [comment]
Can you post a more complete code sample? The test passes successfully so the issue must be outside the `vm.defineProperty` snippet.

**Comment by justjake** [comment]
Closing as stale 🤷🏻
