### ISSUE TITLE
How can I add host functions to the VM without using addFunction (my runtime forbids addFunction)?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [justjake/quickjs-emscripten#48]
Im running quick at the edge, so i cannot use addFunction

Few questions:)
1) how would someone add a custom function into quickjs from the stat so that I don't need to use addFunction (like say console.log)
2) since i cannot addFunction because it requires generating a JS->>C host callback, is it possible to or how would someone enable `fetch` or any async capability inside of this project

**Comment by justjake** [comment]
# 1 - Adding custom sync functions without `addFunction`

Based on this Emscripten documentation, it seems like this may be possible?
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript

Here are the rough steps:

1. Fork quickjs-emscripten
1. Define an API in C for whatever function you want to expose, for example `void my_console_log(char* msg);`
1. Implement that C function in your host Javascript code by adding it to `LibraryManager.library`, eg `LibraryManager.library.my_console_log = console.log`. I'm not sure where LibraryManager comes from.
1. Build a QuickJS module with C ([see the QuickJS docs for details](https://bellard.org/quickjs/quickjs.html#QuickJS-C-API)) that calls your `my_console_log` function, and add it during runtime creation here: https://github.com/justjake/quickjs-emscripten/blob/e58ca7bb8a3ddb008fc1bc5ef6406bb9f8a8591f/c/interface.c#L254-L268.

# 2 - Adding custom async functions without `addFunction`

This is much easier if you're willing to use polling. You can set up a `requests` queue and `responses` map globals inside the VM, and rely on the host to pull requests from the queue and put reponse data into the responses map once it's ready.

This is untested but should give you a vague idea.

Host code:

```typescript
async function poll(vm: QuickJSVm) {
  const zero = vm.newNumber(0)
  while (true) {
    // Poll for requests.
    await new Promise(resolve => setTimeout(resolve, 500))

    const requestsHandle = vm.getProp(vm.global, 'requests')
    const queue: Request[] = vm.dump(requestsHandle)
    vm.setProp(requestsHandle, 'length', zero)
    requestsHandle.dispose()

    // Perform any new requests
    for (const request of queue) {
      fetch(request.url, { body: request.body }).then(async response => {
        // Push the response into the VM's response queue
        const jsonResponse: Response = {
          id: request.id,
          status: response.status,
          body: await response.text(),
        }

        vm.unwrapResult(
          vm.evalCode(`responses.set(${request.id}, ${JSON.stringify(jsonResponse)})`)
        ).dispose()
      })
    }
  }
  zero.dispose()
}
```

VM code:

```typescript
requests = []
responses = new Map<number, Response>()
async function fetch(request: Request): Promise<Response> {
  requests.push(request)
  while (true) {
    // Poll for response.
    await new Promise(resolve => setTimeout(resolve, 500))
    const response = responses.get(request.id)
    if (response) {
      responses.delete(request.id)
      return response
    }
  }
}
```

**Comment by justjake** [comment]
My suggestion for the queue to use polling on the VM side doesn't work since the VM doesn't have `setTimeout`. Instead you can use callbacks:

```typescript
async function poll(vm: QuickJSVm) {
  const zero = vm.newNumber(0)
  while (true) {
    // Poll for requests.
    await new Promise(resolve => setTimeout(resolve, 500))

    const requestsHandle = vm.getProp(vm.global, 'requests')
    const queue: Request[] = vm.dump(requestsHandle)
    vm.setProp(requestsHandle, 'length', zero)
    requestsHandle.dispose()

    // Perform any new requests
    for (const request of queue) {
      fetch(request.url, { body: request.body }).then(async response => {
        // Push the response into the VM's response queue
        const jsonResponse: Response = {
          id: request.id,
          status: response.status,
          body: await response.text(),
        }

        vm.unwrapResult(
          vm.evalCode(`responses.get(${request.id})(${JSON.stringify(jsonResponse)})`)
        ).dispose()
      })
    }
  }
  zero.dispose()
}
```

```typescript
requests = []
responses = new Map<number, (response: Response) => void>()
async function fetch(request: Request): Promise<Response> {
  requests.push(request)
  // Wait for resolve to be called by the host.
  return new Promise(resolve => responses.set(request.id, resolve))
}
```

**Comment by ScriptedAlchemy** [comment]
Thank you jake - I'll see what I can do
