### ISSUE TITLE
Is there a way turning async in host to sync in vm?

### ISSUE THREAD

**Issue by yar2001** [justjake/quickjs-emscripten#52]
Hello! Thanks for your great library. I am providing a simple javascript API for user to add custom feature. The user js code will be executed in node server. However, my users don't have too much concept of javascript and I don't want to introduce async/await concept for them. So I'm looking for some way to fetch data from database without letting user write `await` and turn all function into async.

The following code can not work but I hope there is a way to achieve it.
```javascript
vm.newFunction('getNumberFooFromDB', async() => {
  const result = await mongoose.find({...}).exec()
  return vm.newNumber(result.foo)
}).consume(fnHandle => vm.setProp(vm.global, 'getNumberFooFromDB', fnHandle))

vm.unwrapResult(vm.evalCode(`const foo=getNumberFooFromDB(); foo+1`))
```
Traditional vm solution such as  vm2 and ShadowRealm can not work. Some old js interpreter in js can only support es5. Directly blocking js thread to convert async has performance issue. Modifying the AST and regenerating has some boundary cases. The only way to do this is to develop an interpreter, quickjspp seems able to do this but a lot of uncertainty factor to handle. Is it possible to achieve it in an ease way?

I also found some [background information](https://emscripten.org/docs/porting/asyncify.html).

**Comment by justjake** [comment]
Yeah, I’ve thought about this before as well. You’re right to bring up ASYNCIFY, which is a possible path forward. We could do a second build of QuickJS with -O3 and an asyncify wrapper function around this function: https://github.com/justjake/quickjs-emscripten/blob/8b177552efcd24394a2f31655e3101f47d26a37f/c/interface.c#L93

But, ASYNCIFY is a very big hammer for this problem, meant to work around C-level issues. We might be able to find a way around the issue in QuickJS’s C api.

**Comment by justjake** [comment]
I’ve checked, it seems impossible to use the C API to suspend the VM execution state. So, the options are ASYNCIFY, or do something strange: you can write your own suspense logic, because you control the script execution.

Whenever the user code would need to suspend to await a promise, throw the promise instead. Catch the promise at the top level, and await it. Once it’s ready, re-run the user code, but return the unwrapped promise result when the user code calls the async function again. Continue until you reach completion or hit a CPU or time budget. 

For that idea to work, you need to ensure that your users’ code is as pure as possible, so that when you re-run it, it doesn’t diverge on subsequent runs, and so it doesn’t trigger effects multiple times.

**Comment by yar2001** [comment]
Thanks for the advice! Actually, I have considered this method. However, user may use `Math.rand` or `Date`. Overriding it by static rand seed or other solution seems will solve the problem, but I think it is not general. I want to design an API for users of many levels and I can't make sure that this won't conflict with future plans.

I'm new to wasm, and after one day of exploration, I finally got what your "ASYNCIFY is a very big hammer" means. Perhaps I will try C++ with Embind. If I get anything good, I'll let you know.

**Comment by yar2001** [comment]
I was unable to get an ideal way to achieve that. However, I found a way to execute async function by "polling". It's not elegant but it works.
Here is the prototype:
```cpp
//async.cpp
#include <emscripten.h>
#include <emscripten/bind.h>
#include <map>
#include <iostream>

using namespace emscripten;

std::map<int, bool> fnWaitMap;
std::map<int, bool> fnRetMap;

void exeucteAsync(int fnId)
{
  float (*f)(int) = reinterpret_cast<float (*)(int)>(fnId);
  f(7);
  fnWaitMap[fnId] = false;
  while (!fnWaitMap[fnId])
  {
    emscripten_sleep(4);
  }
  EM_ASM_(Module.removeFunction($0), f);
  std::cout << "Output " << fnRetMap[fnId] << std::endl;
}

void asyncResolve(int fnId, int ret)
{
  fnWaitMap[fnId] = true;
  fnRetMap[fnId] = ret;
}

EMSCRIPTEN_BINDINGS(my_module)
{
  function("execute", &exeucteAsync);
  function("asyncResolve", &asyncResolve);
}
```
(it can also work in c, not limited to the cpp)
```js
//async.try.js
const Module = require('./async.js');

function executeAsync(fn) {
  const fnId = Module.addFunction((parm) => {
    fn(parm).then((ret) => {
      Module.asyncResolve(fnId, ret);
    });
  }, 'fi');

  return Module.execute(fnId);
}

Module.onRuntimeInitialized = () => {
  executeAsync(async (a) => {
    await new Promise((resolve) => setTimeout(() => resolve(), 1000));
    return a ** 2;
  });
};

setInterval(() => {
  console.log('thread is not block!');
}, 1000);
```

```shell
emcc -o async.js --bind async.cpp -s ALLOW_TABLE_GROWTH -s EXPORTED_RUNTIME_METHODS='["cwrap", "addFunction", "removeFunction", "stringToUTF8", "lengthBytesUTF8"]' -O3 -s ASYNCIFY
node async.js
```

And the result should be:

![image](https://user-images.githubusercontent.com/20311434/149661408-505a0a8d-3c15-4a97-9c8f-8f90e2b401b1.png)

The key point is [emscripten_sleep](https://emscripten.org/docs/porting/asyncify.html#sleeping-yielding-to-the-event-loop). It can let wasm wait without block the thread.

**Comment by justjake** [comment]
> The key point is emscripten_sleep. It can let wasm wait without block the thread.

true, but any function that calls down to emscripten_sleep is going to be suspended - it’s stack unwound and stored by ASYNCIFY. That means that even using polling, the compiler will need to ASYNCIFY all of quickjs, which might lead to some issues. So, I don’t see much advantage to using this polling method over a direct async call of your APIs. 

After reading your issue the other day, I found someone else worked on ASYNCIFYing quickjs-emscripten in a fork and asked them about it on Twitter: https://twitter.com/louroboros/status/1481689244603072513?s=21

it seems like they originally tried using ASYNCIFY but encountered some challenges so they removed it in this commit. But, maybe you could continue their work from the parent commit? It looks like a good start: https://github.com/namuol/quickjs-emscripten--modules-support/commit/29c816bcab1d30c32976f306662c3ab99177064c

**Comment by yar2001** [comment]
> That means that even using polling, the compiler will need to ASYNCIFY all of quickjs, which might lead to some issues.

Sorry, I don't get it. Won't ASYNCIFY all of quickjs is an expected behavior? Because from quickjs perspective, the thread of sync function is blocked until the async function in host releases it. Will there exist a solution to achieve ASYNCIFY without freezing all the quickjs? Do I miss something? 
Or are you indicating that it will influence multiple QuickJSVm instances?
The reason I use polling method is because I fail to find a way to execute async function pointer directly. All the pages of asyncify in [manual](https://emscripten.org/docs/porting/asyncify.html) is about asyncifying Web APIs. I'm not familiar with emscripten yet. But after your reply, now I know that I can directly call function outside the VM by `EM_ASYNC_JS`.

**Comment by justjake** [comment]
@yar2001 I've started a PR to add an ASYNCIFY build variant and a new API surface for dealing with asyncified QuickJS interactions here: #54

I'm still figuring out the best way to offer both sync and async APIs, how to support existing code that expects everything to be sync, etc.

**Comment by Macil** [comment]
Besides using an ASYNCIFY build, a strategy that works now is to run quickjs-emscripten inside of a separate worker thread, have the worker thread and the main thread share a SharedArrayBuffer, and then at any time your code in the worker thread can communicate to the main thread through the SharedArrayBuffer and use `Atomics.wait()` to block the worker until the main thread responds. There's some discussion of the technique here: https://github.com/pyodide/pyodide/issues/1219

**Comment by justjake** [comment]
I got the asyncified function API passing a test this morning in #54. There’s still a bit of work left on async module loading, though.

**Comment by yar2001** [comment]
OMG thank you so much for your amazing work, this may be the first elegant solution in the entire community for asynchronous to synchronous. 
I'm really sorry that I can't give you a hand. I'm busy preparing for my undergraduate internship interview recently, but my project and my users still need it very much. I will try this scheme when I have time later. Thanks again!

**Comment by yar2001** [comment]
Nice, I migrated from vm2 to quickjs-emscripten, and it works great! The old temporary solution is to fetch all the data user codes needed which is really slow, and the new asyncify solution gives me a lot of room to optimize performance.

Besides, quickjs-emscripten has better memory and resource control, and be able to control many of the security vulnerabilities I know so far such as unceasing promise and thread blocking. (Surely don't need to care about prototype chain pollution, global scope leakage since the VM is absolutely isolated from the host)

There are also spillover effects, that I can use the sandbox in both browser and server. The sharing of code and the consistent code behavior greatly enhances the development and debugging efficiency. In the near future, I will develop an interactive teaching program for my users and it will be very useful for sandbox execution in the browser.

For anyone who is investigating the JS sandbox technology stack, quickjs-emscripten would be a good choice. I would recommend this framework to anyone around who needs it.
