### ISSUE TITLE
Exposing a handle for a function inside the VM to the host

### ISSUE THREAD

**Issue by fabiospampinato** [justjake/quickjs-emscripten#53]
I'm trying to use this library for building a secure plugins system, and one of the important things that plugins should be able to do is pass callbacks to the host system, the problem is as far as I'm understanding there's currently only basic support for passing JSON-serializable values back and forth, and for passing functions from the host to the vm, but not the other way around.

What would the best way to implement something like that given the provided APIs?

I'm thinking perhaps functions could be serialized into something like `{ __uniqueFnId: 123 }`, which then could be passed successfully to the host, and the host could ask the guest to execute that function, which the guest should be able to resolve. It sounds hacky though, is there maybe a much better way to do this kind of things currently?

**Comment by justjake** [comment]
The host can get a handle to any kind of value, including function handles. You can use `vm.callFunction(fnHandle, thisHandle, …argHandles)` to call a function handle. See https://github.com/justjake/quickjs-emscripten/blob/master/doc/classes/quickjsvm.md#callfunction and the tests for examples (eg https://github.com/justjake/quickjs-emscripten/blob/8b177552efcd24394a2f31655e3101f47d26a37f/ts/quickjs.test.ts#L66). 

The other question you are asking is, “how to I serialize complex values into and out of the VM?”. The focus of this library is exposing a secure interface to using the QuickJS VM for untrusted code, and for that reason I don’t provide any automatic serializing or deserializing. It’s your responsibility to selectively serialize or deserialize the specific object shapes you expect. See this Figma blog post for a more detailed description on implementing a plugin system: https://www.figma.com/blog/how-we-built-the-figma-plugin-system/
