### ISSUE TITLE
How to send class to quickjs vm

### ISSUE THREAD

**Issue by jimizai** [justjake/quickjs-emscripten#56]
I'm having a problem where I declare a class in the browser, but I can't send the class into the quickjs vm by using the current API.
After I looked at the implementation of newFunction, I found that it is just a function call, my appeal is how to send a function to quickjs.

**Comment by jimizai** [comment]
I'm considering whether I can send the string code into quickjs, and then use new Function or eval to create the corresponding method. I wonder if you will add such an api in the future?

**Comment by justjake** [comment]
I’m currently focused on exposing more lower level APIs from the QuickJS C library. You can check out “quickjs-emscripten-sync”, which I believe offers some degree of automatic marshaling of objects.

**Comment by jimizai** [comment]
OK，Thanks!
