### ISSUE TITLE
Error with NextJS

### ISSUE THREAD

**Issue by nicobytes** [justjake/quickjs-emscripten#62]
Hello, first is incredible work this package. It's amazing.

I attempted to use this package in my NextJS project, but I received the following error:

![image](https://user-images.githubusercontent.com/7611944/170541843-5a0867d2-6a78-4e83-8158-731e45d68553.png)

My component is like that:

```tsx
import { useEffect, useState } from 'react';
import { getQuickJS } from 'quickjs-emscripten';

export default function QuickJS() {
  const [rta, setRta] = useState<unknown>(0);

  const runCode = async () => {
    const QuickJS = await getQuickJS();
    const rta = QuickJS.evalCode(`1 + "1"`);
    setRta(rta);
  };

  useEffect(() => {
    runCode();
  });

  return <h1>{rta}</h1>;
}
```
I guess the error is because NextJS has a hydration process. The package first detects the node environment and then, with NextJS hydration run in the browser, the environment keeps with the node and enters this statement.

![image](https://user-images.githubusercontent.com/7611944/170542006-345d7451-65f7-4f38-aac5-a1d58ae9beea.png)

It's just my guess, when this package from the server works, for example,

```tsx
import { getQuickJS } from 'quickjs-emscripten';

export default function QuickJS({ rta }) {
  return <h1>{rta}</h1>;
}

export const getServerSideProps = async () => {
  const QuickJS = await getQuickJS();
  const rta = QuickJS.evalCode(`1 + "1"`);
  return {
    props: {
      rta,
    },
  };
};

```

But the idea is run quickjs from client side.

**Comment by justjake** [comment]
Error is unrelated to hydration. The issue is that fs is a Node standard library module, but the code is running in the browser, not Node. 

See guide here: https://github.com/justjake/quickjs-emscripten/issues/33#issuecomment-739098440
