### ISSUE TITLE
Could it support vm.newSymbol()?

### ISSUE THREAD

**Issue by fake-car** [justjake/quickjs-emscripten#71]
There are many scenes of using Symbol, but I cant make it with vm.newSymbol. I see `JS_NewAtomWithSymbol` and `JS_SymbolGetIterato` in quickjs. Can you add it? Really appreciate it.

**Comment by justjake** [comment]
I’m happy to accept a PR for this. 

The README should cover how the Typescript API is generated for C functions. is there any more guidance you need?
