### ISSUE TITLE
How to do setInterval function?

### ISSUE THREAD

**Issue by UntrustableRus** [justjake/quickjs-emscripten#73]
I have the following:
```js
var _setInterval = vm.newFunction("setInterval", (...args) => {
            const nativeArgs = args.map(vm.dump);
            console.log(...nativeArgs)
            return vm.newNumber(setInterval(...nativeArgs));
});
vm.setProp(vm.global, "setInterval", _setInterval);
_setInterval.dispose();
```

and the following code is ran in the quickjs sandbox:
```js
setInterval(function() {
      console.log("a");
}, 2000);
```
This doesn't work. I get an error:
```
Uncaught SyntaxError: Function statements require a function name
```
Even when I do set a function name like so:
```js
setInterval(function q() {
      console.log("a");
}, 2000);
````
It still doesn't work, nothing is outputted to console, not even an error.

**Comment by justjake** [comment]
What do you think vm.dump is doing to that function argument? I think it’s turning it into a string. It’s certainly not turning it into a function!

**Comment by UntrustableRus** [comment]
I’m sorry, I am very new to this and just was basing things off the
examples. Could you tell me how to do this correctly?

**Comment by UntrustableRus** [comment]
bump

**Comment by justjake** [comment]
vm.dump uses JSON serialization. It can’t turn a VM function into a host function, so you can’t pass it to setInterval and expect things to work flawlessly.

First, dup the Function handle. Then, pass host function literal to setInterval, and call vm.callFunction(functionHandle).

**Comment by UntrustableRus** [comment]
okay, but how do I run that code in the context of the file that it was ran on, so if a variable or something is defined outside of the setInterval, how would I access that inside the setInterval?

**Comment by justjake** [comment]
That should "just work" if you're using a QuickJSHandle instead of `vm.dump(handle)`. Normal scoping / closure rules apply inside the VM.

**Comment by UntrustableRus** [comment]
> That should "just work" if you're using a QuickJSHandle instead of `vm.dump(handle)`. Normal scoping / closure rules apply inside the VM.

Once again I apologize for my lack of experience- how do I do a QuickJSHandle?

**Comment by justjake** [comment]
The arguments to the function you pass to newFunction all have type QuickJSHandle. See the docs: https://github.com/justjake/quickjs-emscripten/blob/main/doc/modules.md#vmfunctionimplementation

I’m closing this issue for now because there doesn’t seem to be a bug in the library or docs, and I don’t have free time to spend on additional examples right now.

**Comment by UntrustableRus** [comment]
Thanks, but it's still going over my head. I apologize for my lack of knowledge, but I'd really appreciate an example because I am still lost. In the future, improving documentation can go a long way.

**Comment by OmarShehata** [comment]
In case it helps others in the future, here is an example of creating `setTimeout`:

```javascript
const _setTimeout = vm.newFunction("setTimeout", (vmFnHandle, timeoutHandle) => {
  // Make a copy because otherwise vmFnHandle does not live long enough to call after the timeout
  const vmFnHandleCopy = vmFnHandle.dup()
  const timeout = vm.dump(timeoutHandle)
  const timeoutID = setTimeout(() => {
    // callFunction(vmFnHandleCopy) will call the vm function
    // in the context of the vm
    // we pass vm.undefined because we need to pass something for the "this" argument
    vm.callFunction(vmFnHandleCopy, vm.undefined)
  }, timeout)
  
  return vm.newNumber(timeoutID);
});

vm.setProp(vm.global, "setTimeout", _setTimeout);
_setTimeout.dispose();
```
