### ISSUE TITLE
Use vm.dump function dump a Symbol get an empty string

### ISSUE THREAD

**Issue by ahaoboy** [justjake/quickjs-emscripten#77]
Symbol is [primitive data type](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) so it's behaviour should same as undefined/null
```
  const qjs = await getQuickJS()
  const vm = qjs.newContext()
  const sym = vm.unwrapResult(vm.evalCode(`Symbol(1)`))
  console.log(vm.dump(sym)) // ""
```

**Comment by justjake** [comment]
Currently this is implemented with JSON.stringify here: https://github.com/justjake/quickjs-emscripten/blob/f2b5ecdc94fc9dd374f1502577dea2940e9e9c5e/c/interface.c#L426

The documentation describes this function as "best effort" if it cannot be serialized to JSON: https://github.com/justjake/quickjs-emscripten/blob/main/doc/classes/QuickJSContext.md#dump

I'm happy to merge a PR improving the situation.
