### ISSUE TITLE
WebAssembly.instantiate(): table import has no maximum length

### ISSUE THREAD

**Issue by eliot-akira** [justjake/quickjs-emscripten#8]
When I clone the repo and install, I'm getting a RuntimeError.

```
git clone https://github.com/justjake/quickjs-emscripten
cd quickjs-emscripten
yarn
```

After `yarn make-release` and `tsc` finish, the test runs:

```
failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): table import 21 has no maximum length, expected 618
[LinkError: WebAssembly.instantiate(): table import 21 has no maximum length, expected 618]
[LinkError: WebAssembly.instantiate(): table import 21 has no maximum length, expected 618]
RuntimeError: abort(LinkError: WebAssembly.instantiate(): table import 21 has no maximum length, expected 618). Build with -s ASSERTIONS=1 for more info.
    at C (~/quickjs-emscripten/dist/quickjs-emscripten-module.js:161:55)
    at /quickjs-emscripten/dist/quickjs-emscripten-module.js:186:175
```

I tentatively searched for a cause, but couldn't find much information about this error.

It feels like a compatibility issue (?) so I checked with `emcc -v`.

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.18
clang version 6.0.1  (emscripten 1.39.18 : 1.39.18)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
shared:INFO: (Emscripten: Running sanity checks)
```

Node.js version is `v12.14.1`.

**Comment by justjake** [comment]
I agree that your issue sounds like a compiler mismatch.

My `emcc -v`: 

```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.5
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project be2b7ea89ab43d6827634fbdbbd2661e1f242527)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Users/jitl/bundles/emsdk/upstream/bin
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by eliot-akira** [comment]
Hi @justjake - Thank you for the response.

I see, `emcc` on my end was using clang 6.x for some reason - even though `clang -v` shows 10.x. After trying to set it via environment variables and `~/.emscripten`, I decided to reinstall Emscripten.

Previously, I installed it using `brew install emscripten`. This time I manually installed it by following the [directions in emscripten.org](https://emscripten.org/docs/getting_started/downloads.html#installation-instructions). Now `emcc -v` looks similar to yours.

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.18
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 613c4a87ba9bb39d1927402f4dd4c1ef1f9a02f7)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Users/eliot/e/wasm/emsdk/upstream/bin
```

---

When I run `yarn build`, I'm seeing a different error.

```
ts/ffi.ts:67:17 - error TS2339: Property 'cwrap' does not exist on type 'EmscriptenModule'.

67     this.module.cwrap("QTS_SetHostCallback", null, ["number"])
                   ~~~~~
```

It shows this for every occurence of `.cwrap()`.

I wonder, did the interface of `EmscriptenModule` have a breaking change? I checked [its type definition in `@types/emscripten`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6cd64665e8bd6776fd7fbdf0723fa8befc68d1da/types/emscripten/index.d.ts#L43), and indeed it does not have a `cwrap` method.

**Comment by eliot-akira** [comment]
Just to explore further, I was able to make it compile by mock/declaring the method in `QuickJSFFI`.

```ts
constructor(private module: EmscriptenModule & { cwrap?: any }) {}
```

After compilation, the test runs with the following result.

```
Uncaught abort(RuntimeError: abort(You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js) at Error:
    at b (/Users/eliot/wasm/quickjs-emscripten/ts/quickjs-emscripten-module.js:80:88)
    at Promise.set (/Users/eliot/wasm/quickjs-emscripten/ts/quickjs-emscripten-module.js:54:423)
    at /Users/eliot/wasm/quickjs-emscripten/ts/quickjs.ts:28:37
```

It seems like this is another symptom of the same issue, as you said, compiler version mismatch of some kind.

So I'm running emcc 1.39.18 - perhaps I'll try 1.39.5 as you have. Looking at the version numbers, there shouldn't have been any big changes though..

**Comment by justjake** [comment]
For this error:

```
Uncaught abort(RuntimeError: abort(You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js) at Error:
    at b (/Users/eliot/wasm/quickjs-emscripten/ts/quickjs-emscripten-module.js:80:88)
    at Promise.set (/Users/eliot/wasm/quickjs-emscripten/ts/quickjs-emscripten-module.js:54:423)
    at /Users/eliot/wasm/quickjs-emscripten/ts/quickjs.ts:28:37
```

I don't know what else this could be other than changes between emcc versions changing the interface of the generated emscripten module. The public @types/emscripten is rough, and was causing issues for some quickjs-emscripten consumers, so I've redeclared the interface that quickjs-emscripten actually uses in https://github.com/justjake/quickjs-emscripten/blob/master/ts/emscripten-types.ts. Those types match what's generated by *my* emcc compiler 😏.

I installed 1.39.5 by unzipping a tarball from the emscripten website. Maybe try picking up the same version I use?

**Comment by eliot-akira** [comment]
Success!

In the end, I created an Ubuntu VM so I can explore different setups. Following the [install guide](https://emscripten.org/docs/getting_started/downloads.html), I made sure to get the specific version of Emscripten with:

```sh
./emsdk install 1.39.5 && ./emsdk activate 1.39.5
```

(As an aside, had to alias `python` to `python2.7` to get `emcc` to run.)

Now `emcc -v` shows:

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.5
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project be2b7ea89ab43d6827634fbdbbd2661e1f242527)
```

..and the following works - it builds and passes all tests.

```sh
git clone https://github.com/justjake/quickjs-emscripten
cd quickjs-emscripten
yarn
```

So, I'll go ahead and close this issue. Thank you very much for the help.

It may be something to keep an eye out for the future, about possible change in interface generated by Emscripten.

**Comment by eliot-akira** [comment]
..Actually, I learned that I can switch `emcc` versions using the `emsdk` command, so I explored a bit more.

From my local install of `emsdk`, I listed available versions:

```sh
./emsdk list
```

..then installed and activated the latest version of Emscripten:

```sh
./emsdk install 1.38.48 && ./emsdk activate 1.38.48
source ./emsdk_env.sh
```

When I go back to the `quickjs-emscripten` repo and run `yarn`, it exhibit the same symptom as I was seeing on macOS, during the test:

```
Uncaught Error: the string "abort(abort(LinkError: WebAssembly.instantiate(): table import 24 has no maximum length, expected 604). Build with -s ASSERTIONS=1 for more info.)
```

I'm totally fine with using a specific pinned version of `emcc`, but I figured this info might be useful anyway.

**Comment by eliot-akira** [comment]
OK, I ran through and checked emcc versions above 1.39.5, with iterations of:

```sh
version=1.39.6 && cd ~/emsdk && ./emsdk install $version && ./emsdk activate $version && source ./emsdk_env.sh && cd ~/quickjs-emscripten && yarn
```

All versions built and passed tests, until `1.39.12`. There, emsdk itself had a Python error.

Then I tried emcc version `1.39.15`. Yes, quickjs-emscripten _does_ build, and passes all tests.

On versions `1.39.16~18`, the test fails with two errors inside "before each" and "after each", respectively:

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/sandbox/quickjs-emscripten/dist/quickjs.test.js)

TypeError: Cannot read property 'dispose' of undefined
```

Oh, I wonder what happened to the `WebAssembly.instantiate` error that I described in the previous comment..

Well, the breaking point seems to be **emcc 1.39.16**.  In their release notes, I referred to the [change log](https://emscripten.org/docs/introducing_emscripten/release_notes.html#changelog) for that version. It's a big list of changes - I don't know if it's related, but here's the most notable one:

> Change the factory function created by using the `MODULARIZE` build option to
>   return a Promise instead of the module instance. That is, beforehand
> 
>         Module()
> 
>   would return an instance (which was perhaps not ready yet if startup was
>   async). In the new model, that returns a Promise which you can do `.then` or
>   `await` on to get notified when the instance is ready, and the callback
>   receives the instance. Note that both before and after this change
>   doing `Module()` creates and runs an instance, so the only change is
>   the return value from that call.
>
>   This fixes some long-standing bugs with that option which have been reported
>   multiple times, but **is a breaking change** - sorry about that. To reduce the
>   risk of confusing breakage, in a build with `ASSERTIONS` we will show a clear
>   warning on common errors. For more, see detailed examples for the current
>   usage in `src/settings.js` on `MODULARIZE`. (#10697)

**Comment by justjake** [comment]
Great research, thank you again. It sounds easy enough to update the library past emcc 1.39.16, and that some install instructions on emsdk are in order in our README.md.
