### ISSUE TITLE
Bundle size too big because of debug

### ISSUE THREAD

**Issue by Hades32** [justjake/quickjs-emscripten#95]
I ran `npx source-map-explorer build/static/js/2.fd64766a.chunk.js build/static/js/2.fd64766a.chunk.js.map --html > size.html` on your `website` example and got this: https://tan-glynis-42.tiiny.site/

It seems to me that release _and_ debug builds are somehow included, so the package could be smaller

**Comment by justjake** [comment]
Yes, this is something I’d like to address. I made an attempt to produce a module-native build about a year ago, but ran into substantial issues with Typescript’s build modes at the time. I think the situation has improved to the point that this may be easier to do without involving a bundler like ESBuild or Rollup. Bundlers are fine but I’d like to avoid the extra complexity.

**Comment by justjake** [comment]
Update: Bundlephobia reports the library size as 10kb now 🎉 https://bundlephobia.com/package/quickjs-emscripten@0.22.0.
