### ISSUE TITLE
Getting it to run on Cloudflare Workers 

### ISSUE THREAD

**Issue by Hades32** [justjake/quickjs-emscripten#96]
...and other V8 based runtimes probably.

I'm currently trying to use this on Workers and eventually I figured out that there is one main issue:
https://github.com/cloudflare/wrangler2/issues/1366#issuecomment-1172255671

TLDR: On workers WASM must be included via `import foo from "foo.wasm"` and can't by compiled dynamically via a string param.

Would it be possible to change / allow loading to this way?

**Comment by justjake** [comment]
This is allowed already although it’s not documented. Emscripten modules can have their WASM module overridden. You can try doing so by reading over our code in variants.ts and trying to see where you could inject the WASM module you import in your own code via `import`.

**Comment by danthegoodman1** [comment]
There are a few more issues to cloudflare workers to this that I've found following this

First you need to replace a ton of `{ credentials: "xxx" }` fetch objects with `{}` because fetch does not support that in it's implementation on workers.

You also need to do some `global` and `self` overriding because `self.href` does not exist.

Here is my code so far:


```ts
import { newQuickJSAsyncWASMModule } from 'quickjs-emscripten'

export default {
	async fetch(
		request: Request,
		env: Env,
		ctx: ExecutionContext
	): Promise<Response> {
		(global as any).window = self as any;
		(self as any).location = { href: "/" } as any;

		const m = await newQuickJSAsyncWASMModule()
		const vm = m.newContext()

		const world = vm.newString("world")
		vm.setProp(vm.global, "NAME", world)
		world.dispose()

		let res
		const result = vm.evalCode(`"Hello " + NAME + "!"`)
		if (result.error) {
			console.log("Execution failed:", vm.dump(result.error))
			result.error.dispose()
		} else {
			res = vm.dump(result.value)
			console.log("Success:", res)
			result.value.dispose()
		}

		vm.dispose()

		return new Response("Hello World!");
	},
};
```

Making a request to this leaves with a massive b64 dump ending like:
```
FABBz6wECxUXAAAAABcAAAAACRQAAAAAABQAABQAQf2sBAsBFgBBia0ECycVAAAAABUAAAAACRYAAAAAABYAABYAADAxMjM0NTY3ODlBQkNERUYAQdStBAsBCQBB/K0ECwj//////////wBBxK4ECx0DAAAAAAAAAAIAAAAAAAAAAQAAAAEAAAABAAAABQBB7K4ECwJ2AQBBhK8ECwt3AQAAeAEAAJgcAQBBnK8ECwECAEGsrwQLCP//////////AEHwrwQLCWAXAQAAAAAABQBBhLAECwJ5AQBBnLAECw53AQAAegEAAKgcAQAABABBtLAECwEBAEHEsAQLBf////8KAEGIsQQLB/gXAQCgIlE=";if(!V.startsWith(U)){var
  xa=V;V=a.locateFile?a.locateFile(xa,v):v+xa}function ya(){var b=V;try{if(b==V&&H)return new
  Uint8Array(H);var c=D(b);if(c)return c;if(y)return y(b);throw"both async and sync fetching of
  the wasm failed";}catch(d){G(d)}}
                                                                         ^
      at G
  (/Users/dangoodman/code/test-quickjs-worker/node_modules/quickjs-emscripten/ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:21:71)
      at
  (/Users/dangoodman/code/test-quickjs-worker/node_modules/quickjs-emscripten/ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:36:414)


✘ [ERROR] Uncaught (in response) CompileError: Aborted(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
```

Possibly `newQuickJSAsyncWASMModule()` is not the correct one I was supposed to use from the `variants.ts` file?

**Comment by danthegoodman1** [comment]
I have also noticed there is a significant delay in request processing before this error throws

**Comment by Hades32** [comment]
Thanks Jake, I'll look into that.

Dan, I think the fetch code won't be used when the module is loaded via an import

**Comment by justjake** [comment]
@Hades32 @danthegoodman1 I think the changes in 0.25.0 should make it much easier to get quickjs-emscripten in Cloudflare Workers.

**Comment by justjake** [comment]
I tried it out, and there's a bunch of challenges.

**Comment by justjake** [comment]
I just release v0.26.0, which supports Cloudflare Workers with some setup. See the instructions here: https://github.com/justjake/quickjs-emscripten#webassembly-loading
